### ISSUE TITLE
Add auth logging

### ISSUE THREAD

**Issue by letterj** [getcfs/megacfs#216]
In fs_api.go,  functions auth and validateToken have no logging so it's difficult to troubleshoot.

**Comment by gholt** [comment]
I added a bunch of logging during a refactor. See https://github.com/getcfs/megacfs/blob/master/formic/server/grpcwrapper.go#L731 or https://github.com/getcfs/megacfs/commit/0397012d1438e4e872737c5635682f7ba26deeb8
