### ISSUE TITLE
logging needs file name

### ISSUE THREAD

**Issue by letterj** [getcfs/megacfs#330]
Current log ling for operations in formic is Delete return point 2   {"name": "cfsd", "keyA": 3461159609376659737, "keyB": 7233356897439815981, "childKeyA": 15995901510843142485, "childKeyB": 9469247627055243884, "timestampMicro": 1490824348785599}

The object name would be helpful too.

**Comment by gholt** [comment]
That log line is from the client connection to the group store. That code has no idea what it is storing at that point; could be directory entries, could be account metadata, etc.

Probably a good idea to change the "name" field to "cfsd.groupstore" or something though.
